### ISSUE TITLE
docs badge still says "unknown"

### ISSUE THREAD

**Issue by Nathaniel-Haines** [LedgerInvesting/bayesblend#40]
In the README, our `docs` bade is still showing as "unknown" despite RTD (and the package) being public now: 

<img width="1200" alt="Screenshot 2024-04-19 at 5 18 31 PM" src="https://github.com/LedgerInvesting/bayesblend/assets/25613611/dd18aa99-bf68-489b-89fa-7f9233873c04">

**Comment by cmgoold** [comment]
Passing now @Nathaniel-Haines.
